/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;
import javafx.scene.shape.Line;

/**
 *
 * @author Ambrosio
 */
public class Panel1 extends javax.swing.JPanel {
    private LinkedList<Point> puntos;
    private LinkedList<Line> lineas;
    /**
     * Creates new form Panel1
     */
    
    
    public Panel1() {
        initComponents();
        this.puntos = new LinkedList<>();
        this.lineas = new LinkedList<>();
        
    }
    
    public void adicionarPunto(Point p){
        puntos.add(p);
        repaint();
    }
    
    public void adicionarLinea(Line l){
        this.lineas.add(l);
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        if(!puntos.isEmpty()){
            for (Point punto : this.puntos) {
                g.fillOval((int)punto.getX()-2, (int)punto.getY()-2, 3, 3);
                 
            }
        }
        
        if(!lineas.isEmpty()){
            for (Line linea : this.lineas) {
                g.drawLine((int)linea.getStartX(), (int)linea.getStartY(), (int)linea.getEndX(), (int)linea.getEndY());
                 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the puntos
     */
}
