/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cuadrado;
import Modelo.Linea;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;

/**
 *
 * @author Ambrosio
 */
public class Panel1 extends javax.swing.JPanel {

    private LinkedList<Point> puntos;
    private LinkedList<Linea> lineas;
    private LinkedList<Cuadrado> cuadrados;

    /**
     * Creates new form Panel1
     */

    public Panel1() {
        initComponents();
        this.puntos = new LinkedList<>();
        this.lineas = new LinkedList<>();
        this.cuadrados = new LinkedList<>();

    }

    public void adicionarPunto(Point p) {
        getPuntos().add(p);
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        if(!this.cuadrados.isEmpty()){
            for (Cuadrado cuadrado : this.getCuadrados()) {
                cuadrado.dibujarCuadrado(g);
            }
        }
        if (!this.lineas.isEmpty()) {
            
            g.setColor(Color.black);
            for (Linea linea : lineas) {
                g.drawLine((int) linea.getIni().getX(), (int) linea.getIni().getY(), (int) linea.getFin().getX(), (int) linea.getFin().getY());
            }
        }
        if (!this.puntos.isEmpty()) {
            g.setColor(Color.red);
            for (Point punto : this.getPuntos()) {
                g.fillOval((int) punto.getX() - 2, (int) punto.getY() - 2, 4, 4);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the puntos
     */
    public LinkedList<Point> getPuntos() {
        return puntos;
    }

    /**
     * @param puntos the puntos to set
     */
    public void setPuntos(LinkedList<Point> puntos) {
        this.puntos = puntos;
    }

    /**
     * @return the lineas
     */
    public LinkedList<Linea> getLineas() {
        return lineas;
    }

    /**
     * @param lineas the lineas to set
     */
    public void setLineas(LinkedList<Linea> lineas) {
        this.lineas = lineas;
        this.repaint();
    }

    /**
     * @return the cuadrados
     */
    public LinkedList<Cuadrado> getCuadrados() {
        return cuadrados;
    }

    /**
     * @param cuadrados the cuadrados to set
     */
    public void setCuadrados(LinkedList<Cuadrado> cuadrados) {
        this.cuadrados = cuadrados;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * @return the puntos
     */
}
